[[redirects]]
  from = "/api/"
  to = "https://api.mangadex.org/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"